site_name: "Areen Churi"
site_url: "https://areenchuri.github.io"
nav:
  - Home: index.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.footer
  
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/brightness-4 
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  font:
    text: Montserrat
    code: Montserrat

extra:
  generator: false
  social:
  - icon: "fontawesome/brands/instagram"
    link: "https://www.instagram.com/areen.churi/"
  - icon: "fontawesome/brands/github"
    link: "https://www.github.com/Areen-Churi"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - footnotes
